kookmin-sw/capstone-2024-30

front/capstone_front/.gitignore, front/capstone_front/lib/test.dart
gitignore 수정
Issue Number : #18 
gitignore에 파이어베이스 관련 파일들 추가
=> refactor: #18/gitignore 수정

front/capstone_front/assets/translations/ko-KR.json, front/capstone_front/lib/main.dart, front/capstone_front/lib/screens/home_screen.dart, front/capstone_front/lib/screens/speeking_practice/speeking_practice_screen.dart
홈에서 발성 연습 터치 시 발성 연습 페이지가 열림. 테스트용 리스트뷰를 넣어둠
Issue Number : #26 
리스트뷰를 통해 스크롤하여 예문 선택 가능
=> feature: #26/리스트뷰 추가

front/capstone_front/lib/screens/login/signup_screen.dart
버그 수정
Issue Number : #27
회원가입 완료 시 로그인 화면이 아닌 메인페이지로 이동하는 버그 수정
resolve #27
=> bug: #27-회원가입 완료 시 메인페이지로 이동하는 버그 수정

front/capstone_front/ios/Podfile, front/capstone_front/ios/Runner.xcodeproj/project.pbxproj, front/capstone_front/ios/Runner/Info.plist
IOS 마이크 권한 추가
Issue Number : #32 
IOS 마이크 권한 추가
> Please provide screenshots of your task if you need.
> Please explain test scope, task, plan, method
close #32
=> fix: #32/ios 마이크로폰 권한추가

front/capstone_front/assets/translations/en-US.json, front/capstone_front/assets/translations/ko-KR.json, front/capstone_front/lib/main.dart, front/capstone_front/lib/screens/cafeteriaMenu/cafeteriaMenuScreen.dart, front/capstone_front/lib/screens/cafeteriaMenu/dateChanger.dart, front/capstone_front/lib/screens/cafeteriaMenu/menuCard.dart, front/capstone_front/lib/screens/home_screen.dart
학식정보 스크린 생성
Issue Number : #15 
- 학식정보 스크린 구현
- 커스텀 캘린더 구현
=> feature: #15/학식정보 스크린 생성

front/capstone_front/assets/translations/en-US.json, front/capstone_front/assets/translations/ko-KR.json, front/capstone_front/lib/main.dart, front/capstone_front/lib/screens/chatbot/chatbot.dart, front/capstone_front/lib/screens/home_screen.dart
챗봇 UI 및 기본적인 기능 제작
Issue Number : #42 
'가이드'를 눌러 챗봇에 들어감
텍스트를 입력하고 전송을 누름
입력한 텍스트가 화면에 보
=> feature: #42-챗봇 UI 및 기본적인 기능 제작

back/Dockerfile, back/docker-compose.yml
Docker랑 Docker Compose 파일 작성해서 Spring 서버 Container화 시켰습니다.
Issue Number : #12 
- Docker 파일 작성
- Docker Compose 파일 작성
- 추후 Redis, Nginx 추가시 Docker Compose에 추가
- Docker로 AWS EC2에 올릴 예정
.env.example을 바탕으로 .env 환경변수를 작성합니다. 
```
./gradlew
```
또는
```
gradle clean build
````
로 .jar 파일을 생성합니다.
```
docker-compose up --build -d
```
를 이용하여 docker compose build를 하여 실행합니다.
Docker한 것을 바탕으로, ReadME에도 실행방법 위와 같이 쓰고, AWS 배포도 Docker로 진행하고자 합니다.
PR 확인해주시면 AWS EC2 인스턴스 설정해서 배포하도록 하겠습니다.
=> feat: #12-Dockerize Backend

front/capstone_front/lib/screens/faq/faq_screen.dart, front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart, front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart, front/capstone_front/lib/services/qna_service.dart
- 제목, 본문이 길때 화면밖으로 overflow 되는 것 해결
- 질문글의 댓글 좋아요 토글 버튼 구현
- 댓글 좋아요 API 구현
- 필터박스 크기 조정
Issue Number : #57
=> Feature: QnA detail 화면 버그 수정 및 댓글 하트 추가, API 구현

.github/workflows/deploy.yml
=> fix: git action 스크립트 수정

back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepositoryImpl.java
DTO 기반 Fetch Join 문제를 해결하였다.
Issue Number : #151 
이전 QuestionImage, FAQImage에서 발생한 문제와 동일한 문제가 발생하여 수정하였다.
=> refactor: #151-DTO기반 Fetch Join 문제 해결 - Answer

.github/workflows/deploy.yml, back-gateway/src/main/resources/application.yml, back/docker-compose.yml, docker-compose.yml
=> git action 스크립트 정리

.github/workflows/deploy.yml
=> fix: secret값들 변경

front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart, front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
> 디테일 화면 스크롤 새로고침, 하단 강제 스크롤 문제 해결
=> feat: #137-qna 디테일 위로 끌어당겨 새로고침, 하단 자동 스크롤 문제 해결

.github/workflows/deploy.yml, back-gateway/src/main/java/com/gateway/backgateway/config/GatewayConfig.java, back/nginx/Dockerfile, back/nginx/default.conf.template
=> fix: api 문서 접근 가능하게 변경

back/src/main/generated/com/example/capstone/domain/help/entity/Qhelp.java, back/src/main/generated/com/example/capstone/domain/qna/entity/QAnswer.java, back/src/main/generated/com/example/capstone/domain/qna/entity/QQuestion.java, back/src/main/java/com/example/capstone/domain/help/controller/HelpController.java, back/src/main/java/com/example/capstone/domain/help/dto/HelpListRequest.java, back/src/main/java/com/example/capstone/domain/help/dto/HelpListResponse.java, back/src/main/java/com/example/capstone/domain/help/dto/HelpPostRequest.java, back/src/main/java/com/example/capstone/domain/help/dto/HelpResponse.java, back/src/main/java/com/example/capstone/domain/help/entity/Help.java, back/src/main/java/com/example/capstone/domain/help/repository/HelpListRepository.java, back/src/main/java/com/example/capstone/domain/help/repository/HelpRepositoryImpl.java, back/src/main/java/com/example/capstone/domain/help/service/HelpService.java, back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java, back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java, back/src/main/java/com/example/capstone/domain/qna/dto/AnswerResponse.java, back/src/main/java/com/example/capstone/domain/qna/dto/QuestionResponse.java, back/src/main/java/com/example/capstone/domain/qna/entity/Answer.java, back/src/main/java/com/example/capstone/domain/qna/entity/Question.java, back/src/main/java/com/example/capstone/domain/qna/service/AnswerService.java, back/src/main/java/com/example/capstone/domain/qna/service/QuestionService.java, back/src/main/java/com/example/capstone/domain/user/dto/SigninRequest.java, back/src/main/java/com/example/capstone/domain/user/repository/UserRepository.java
- UUID 자료형을 String 변경하였다.
- 수정 요청 Endpoint에서 UUID 확인 과정을 추가하였다.
Issue Number : #163
=> Refactor/be/#163 UUID 자료형 String 변경 및 수정 요청 Endpoint에서 UUID 확인 과정 추가

back/src/main/java/com/example/capstone/domain/help/entity/Help.java, back/src/main/java/com/example/capstone/domain/qna/entity/Answer.java, back/src/main/java/com/example/capstone/domain/qna/entity/Question.java
=> Refactor/be/#163 UUID Unique 제거

front/capstone_front/lib/screens/notice/notice_screen.dart, front/capstone_front/lib/services/notice_service.dart
> 공지사항 검색기능 구현
Issue Number : #108 
> 공지사항 검색기능 구현
=> [FE] 공지사항 검색기능 구현

back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCrawlService.java, back/src/main/java/com/example/capstone/domain/menu/service/MenuUpdateService.java
중국어 지원을 위한 ZH 언어설정 추가
Issue Number : #175
=> refactor: #175-중국어 지원을 위한 ZH 언어설정 추가

front/capstone_front/lib/main.dart, front/capstone_front/lib/models/chat_room_model.dart, front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_card.dart, front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_list_screen.dart, front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_room.dart, front/capstone_front/lib/screens/qna/qna_write/qna_write_screen.dart, front/capstone_front/lib/services/chat_service.dart
> 채팅 미리보기 버그 수정
Issue Number : #109 
- 채팅리스트 화면에서 미리보기 관련 발생하였던 버그를 해결함
- API endpoint 변경
- 새로운 메시지가 왔을 때, N이 정상적으로 수정되도록 수정
> Please explain test scope, task, plan, method
=> feat: #109-채팅 미리보기 버그 수정

back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java, back/src/main/java/com/example/capstone/domain/menu/service/MenuUpdateService.java
메뉴 크롤링 작업 수정
Issue Number :
메뉴 크롤링 작업 수정
=> refactor: 메뉴 크롤링 작업 수정

front/capstone_front/lib/screens/helper/helper_board/helper_board_screen.dart
> 헬퍼화면에서 헬피글쓰면 헬퍼화면에서 보이는 버그 수정
Issue Number : #204
=> bug: #204-헬퍼화면에서 헬피글쓰면 헬퍼화면에서 보이는 버그 수정

back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java, back/src/main/java/com/example/capstone/domain/qna/dto/LikeRequest.java, back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepositoryImpl.java
추천시 request body 요청 수정 + 추천 여부 null 반환 수정
Issue Number :
추천시 request body 요청 수정 
추천 여부 null 반환 수정
=> Feature/be/#130 추천시 request body 요청 수정 + 추천 여부 null 반환 수정

.github/workflows/deploy.yml, back/.env.example, back/src/main/java/com/example/capstone/domain/qna/service/ImageService.java, back/src/main/resources/application.properties
CloudFront 적용을 위한 DB내 캐싱된 주소 저장
Issue Number : #232 
S3 객체 주소로 직접 연결 불가능하게 변경
CloudFront의 주소로 객체 접근 가능
반드시 환경변수 추가할 것!!!
=> feat: #232-cloud front 캐싱 주소저장 변경

back-gateway/src/main/java/com/gateway/backgateway/filter/GlobalLoggingFilter.java, docker-compose.yml
Global Filter에서 Logging에서 다운 되는 오류 수정
=> fix : GET 로깅 제외

back/src/main/java/com/example/capstone/domain/menu/service/MenuCrawlingService.java
=> refactor: 메뉴 크롤링 수정
